// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgbmimjxnazkkavyddeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnYm1pbWp4bmF6a2thdnlkZGVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMjAwOTgsImV4cCI6MjA2ODc5NjA5OH0.gYugA35q9rgeRpJ8muEs_UwEka7KTZVziMFZwO814WA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);